name: Create Branch 

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Name of the branch to create"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Create a new branch
      run: |
        BRANCH_NAME=${{ github.event.inputs.branch_name }}
        git checkout -b $BRANCH_NAME
        git push origin $BRANCH_NAME

    - name: Confirm branch creation
      run: echo "Branch '$BRANCH_NAME' created successfully."
